###
# LOGIN
POST  http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
  "email": "geral@rampart.ao",
  "password": "12345678"
}

###
# VERIFY USER LOGGED
GET  http://localhost:4000/api/v1/auth/user-logged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRydGxiNXkwMDAwcXJqNmxocXAzZ2x2IiwiZW1haWwiOiJnZXJhbEByYW1wYXJ0LmFvIiwicm9sZXMiOlsic3VwZXIiXSwiaWF0IjoxNzEwNDYwMTk0LCJleHAiOjE3MTA0OTYxOTR9.XYf7df2ycsjYrI4Dkj7y1Ehaxn9vay7F750QtQRxTgo

###
# CREATE USER [ADMIN COMPANY]
POST  http://localhost:4000/api/v1/company/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRkMmdzaXowMDAwc2RyY3Y0azNrd2Z1IiwiZW1haWwiOiJnZXJhbEByYW1wYXJ0LmFvIiwicm9sZXMiOlsic3VwZXIiXSwiaWF0IjoxNzA5ODIwMTA2LCJleHAiOjE3MDk4NTYxMDZ9.wi3Zrecb0X_3SqOJFXu4EaMltDHPUuLLZnu0gROsDTE

{
  "name": "Helder Cambuta",
  "email": "heldercambuta44@gmail.com",
  "username": "helder44",
  "password": "0912Helder@",
  "roles": ["admin"]
}

###
# CREATE COMPANY
POST  http://localhost:4000/api/v1/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRlOHQ0Zm0wMDAwOWdvOTZmMDk4eXJ2IiwiZW1haWwiOiJoZWxkZXJjYW1idXRhQGdtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTcwOTYzNTQ3OSwiZXhwIjoxNzA5NjM3Mjc5fQ.nnfu7OvIEd6eAQPCpD6Tidy6tZzMtwM0EmhhrwcCisc

{
  "name": "Rampart",
  "email": "info@rampart.ao",
  "website": "www.rampart.ao",
  "description": "Rampart é um boa empresa muito boa."
}

###
# GET ALL COMPANIES
GET  http://localhost:4000/api/v1/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRydGxiNXkwMDAwcXJqNmxocXAzZ2x2IiwiZW1haWwiOiJnZXJhbEByYW1wYXJ0LmFvIiwicm9sZXMiOlsic3VwZXIiXSwiaWF0IjoxNzEwNDYwMTk0LCJleHAiOjE3MTA0OTYxOTR9.XYf7df2ycsjYrI4Dkj7y1Ehaxn9vay7F750QtQRxTgo

###
# GET USERS COMPANY
GET  http://localhost:4000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRydGxiNXkwMDAwcXJqNmxocXAzZ2x2IiwiZW1haWwiOiJnZXJhbEByYW1wYXJ0LmFvIiwicm9sZXMiOlsic3VwZXIiXSwiaWF0IjoxNzEwNDYwMTk0LCJleHAiOjE3MTA0OTYxOTR9.XYf7df2ycsjYrI4Dkj7y1Ehaxn9vay7F750QtQRxTgo

###
# CREATE USER [ADMIN COMPANY]
POST  http://localhost:4000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRydGxiNXkwMDAwcXJqNmxocXAzZ2x2IiwiZW1haWwiOiJnZXJhbEByYW1wYXJ0LmFvIiwicm9sZXMiOlsic3VwZXIiXSwiaWF0IjoxNzEwNDYwMTk0LCJleHAiOjE3MTA0OTYxOTR9.XYf7df2ycsjYrI4Dkj7y1Ehaxn9vay7F750QtQRxTgo

{
  "name": "Helder Cambuta",
  "email": "heldercambuta44@gmail.com",
  "username": "nangazaki",
  "password": "0912Helder@",
  "roles": ["analista"]
}

###
# SHOW LOGS [COMPANY]
GET  http://localhost:4000/api/v1/logs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRydGxiNXkwMDAwcXJqNmxocXAzZ2x2IiwiZW1haWwiOiJnZXJhbEByYW1wYXJ0LmFvIiwicm9sZXMiOlsic3VwZXIiXSwiaWF0IjoxNzEwNDYwMTk0LCJleHAiOjE3MTA0OTYxOTR9.XYf7df2ycsjYrI4Dkj7y1Ehaxn9vay7F750QtQRxTgo

###
# SHOW LOGS [COMPANY]
GET  http://localhost:4000/api/v1/logs/requests?page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRoYXQyaXgwMDAwMXR0YTV2aTVuanBxIiwiZW1haWwiOiJoZWxkZXJjYW1idXRhNDRAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzEwMzI0MjExLCJleHAiOjE3MTAzNjAyMTF9.KXZfpSGWMxiwt4-KYGOVwyBasUuIZ5zExcq42AcRNeI

###
# SHOW LOGS [COMPANY]
GET  http://localhost:4000/api/v1/logs/requests/filters?ip=127.0.0.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRoYXQyaXgwMDAwMXR0YTV2aTVuanBxIiwiZW1haWwiOiJoZWxkZXJjYW1idXRhNDRAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzEwNDU0MTMyLCJleHAiOjE3MTA0OTAxMzJ9.Jf3pQfw8xvP_HUrRgr83r0gqAYO5FSWxZ8OsOFGGUN4


###
# SHOW LOGS [COMPANY]
GET  http://localhost:4000/pentest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbHRoYXQyaXgwMDAwMXR0YTV2aTVuanBxIiwiZW1haWwiOiJoZWxkZXJjYW1idXRhNDRAZ21haWwuY29tIiwicm9sZXMiOlsiYWRtaW4iXSwiaWF0IjoxNzEwNDU0MTMyLCJleHAiOjE3MTA0OTAxMzJ9.Jf3pQfw8xvP_HUrRgr83r0gqAYO5FSWxZ8OsOFGGUN4
